### ISSUE TITLE
Email ID and profile image of user needed

### ISSUE THREAD

**Issue by ant000194** [xiao99xiao/TwitterLoginKit#2]
Hi Xiao

I am using your pod file to login with twitter, Is there any possibility to get Twitter email and profile picture of the user. 
Can you please guide me with sample code.

**Comment by xiao99xiao** [comment]
@ant000194 You can follow the official guide here https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-show and use the oauth tokens and user id obtained via `login` method.

**Comment by ant000194** [comment]
Thank you for your response
